name: heuristic
on: workflow_dispatch
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.12'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          apt install -y adduser base-files bash bash-completion ca-certificates command-not-found coreutils cron dash debconf distro-info-data e2fsprogs fuse3 gettext-base hdparm keyutils libattr1:amd64 libaudit-common libc-bin libc6:amd64 libmagic1:amd64 libmecab2:amd64 libncursesw6:amd64 libpam-runtime libpython3.12-stdlib:amd64 libsensors-config libtirpc-common locales login logrotate lsb-release ltrace mailcap make man-db media-types multipath-tools nano ncurses-base netbase nftables openssl overlayroot procps python3-zope.interface python3.12 python3.12-venv rsyslog screen sudo tar tzdata ucf unixodbc-common usb-modeswitch walinuxagent wget
      - run: |
          make install
      - run: |
          make test
    env:
      ACCEPT_EULA: Y
      BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
      COLUMNS: '200'
      DEBIAN_FRONTEND: noninteractive
      DOTNET_MULTILEVEL_LOOKUP: '0'
      DOTNET_NOLOGO: '1'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOSTNAME: pop-os
      HTTPIE_STDIN_READ_WARN_THRESHOLD: '999'
      HTTPIE_TEST_WITH_PYOPENSSL: '0'
      ImageOS: ubuntu22
      ImageVersion: 20250622.1.0
      LC_CTYPE: C.UTF-8
      LINES: '62'
      MAKEFLAGS: ''
      MAKELEVEL: '1'
      MFLAGS: ''
      PLAT: linux-x86_64
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu22
      PYTEST_VERSION: 8.4.1
      PYTHONNOUSERSITE: '1'
      SHLVL: '1'
      TERM: xterm
      _PYI_LINUX_PROCESS_NAME: sawra
      _PYI_PARENT_PROCESS_LEVEL: '1'
